jessiegram/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

jessiegram/jessiegram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('i18n/', include('django.conf.urls.i18n'))
]

handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path(
            '__debug__/',
            include(
                debug_toolbar.urls
            )
        ),
    )

jessiegram/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'group-create/',
        views.group_create,
        name='group_create'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/delete',
        views.post_delete,
        name='post_delete'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.add_or_delete_like,
        name='add_or_delete_like'
    ),
    path(
        r'set-language/',
        views.set_language,
        name='set_language'
    ),
]

jessiegram/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordResetConfirmView
)

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

jessiegram/templates/includes/footer.html
{% load i18n %}
{% load static %}
<div class="row">
    <div class="col-6 col-md">
        <p>
            © 2021 - {{ year }} Copyright <span class="custom-black"><a class="text-muted" href="{% url 'posts:index' %}">JessieGram</a></span><br>
            Developed by <a class="text-muted" href="https://github.com/feel2code">feel2code</a><br>
            <a class="text-muted" href="{% url 'about:tech' %}">{% trans 'Techs' %}</a><br>
            <br>
            Icons from <a target="_blank" href="https://icons8.com" class="iconslinks">Icons8</a>
        </p>
    </div>
    <div class="col-6 col-md">
        <a href="https://t.me/feel2code"><img src="{% static 'img/telegram.png' %}" width="40" height="40" alt="telegram"/></a>
        <a href="https://www.linkedin.com/in/feliks-nabiullin-2b8181234/"><img src="{% static 'img/linkedin.png' %}" width="50" height="50" alt="linkedin"/></a>
        <a href="https://github.com/feel2code"><img src="{% static 'img/github.png' %}" width="50" height="50" alt="github"/></a>
        <a href="mailto:feliksnab@gmail.com"><img src="{% static 'img/mailto.png' %}" width="45" height="45" alt="mailto"/></a>
    </div>
</div>

jessiegram/templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
    {% load i18n %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"
         aria-label="Fifth navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                {% load static %}
                <img src="{% static 'img/logo.svg' %}"
                     width="108"
                     height="30"
                     class="d-inline-block align-top"
                     alt={% trans 'JessieGram' %}/>
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarsExample05"
                    aria-controls="navbarsExample05"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            </div>
            <div class="col-6"></div>
            <div class="collapse navbar-collapse col-3" id="navbarsExample05">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        {% get_available_languages as langs %}
                        <a class="nav-link dropdown-toggle"
                           href="#"
                           id="dropdown07"
                           data-bs-toggle="dropdown"
                           aria-current="page"
                           aria-expanded="false"
                           style="color:white">{{LANGUAGE_CODE.upper}}</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown07">
                            <li class="nav-item">
                                <a class="nav-link"
                                   style="color: gray"
                                   href="{% url 'posts:set_language' %}?l={{langs.0.0}}">{{langs.0.1}}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   style="color: gray"
                                   href="{% url 'posts:set_language' %}?l={{langs.1.0}}">{{langs.1.1}}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   style="color: gray"
                                   href="{% url 'posts:set_language' %}?l={{langs.2.0}}">{{langs.2.1}}</a>
                            </li>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"
                               aria-current="page"
                               href="{% url 'posts:post_create' %}">
                                {% if view_name == 'posts:post_create' %}
                                    <img src="{% static 'img/new_post.svg' %}"
                                         width="30"
                                         height="30"
                                         alt="new post button"/>
                                {% else %}
                                    <img src="{% static 'img/new_post_inactive.svg' %}"
                                         width="30"
                                         height="30"
                                         alt="new post button"/>
                                {% endif %}
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               {% if view_name == 'posts:profile' %}style="color:white"{% endif %}
                               href="#"
                               id="dropdown03"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">@{{ user.username }}</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                <li>
                                    <a class="dropdown-item" href="{% url 'posts:profile' user.username %}">{% trans 'Account' %}</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'posts:follow_index' %}">{% trans 'Subscriptions' %}</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'posts:group_create' %}">{% trans 'Create group' %}</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:password_change' %}">{% trans 'Change password' %}</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">{% trans 'Logout' %}</a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link"
                               aria-current="page"
                               {% if view_name == 'users:login' %}style="color:white"{% endif %}
                               href="{% url 'users:login' %}">{% trans 'Sign in' %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               aria-current="page"
                               {% if view_name == 'users:signup' %}style="color:white"{% endif %}
                               href="{% url 'users:signup' %}">{% trans 'Sign up' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endwith %}