jessiegram/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

jessiegram/jessiegram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('i18n/', include('django.conf.urls.i18n'))
]

handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path(
            '__debug__/',
            include(
                debug_toolbar.urls
            )
        ),
    )

jessiegram/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'group-create/',
        views.group_create,
        name='group_create'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/delete',
        views.post_delete,
        name='post_delete'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.add_or_delete_like,
        name='add_or_delete_like'
    ),
    path(
        r'set-language/',
        views.set_language,
        name='set_language'
    ),
]

jessiegram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class Group(models.Model):
    def __str__(self):
        return self.title or ''

    title = models.CharField(
        max_length=20
    )
    slug = models.SlugField(
        unique=True
    )
    description = models.CharField(
        max_length=25
    )


class Post(models.Model):
    def __str__(self):
        return self.text[:15] or ''

    text = models.CharField(
        max_length=200,
        verbose_name=_("Post text"),
        help_text=_("Enter post's text")
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name=_('Author')
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='group',
        blank=True,
        null=True,
        verbose_name=_('Group'),
        help_text=_('Related group')
    )
    pub_date = models.DateTimeField(
        _('Created at'),
        auto_now_add=True,
        db_index=True
    )
    image = models.ImageField(
        _('Photo'),
        upload_to='posts/',
    )
    like = models.BooleanField(
        null=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')


class Comment(models.Model):
    def __str__(self):
        return None or ''

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name=_('Comment'),
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name=_('Author'),
    )
    text = models.CharField(
        max_length=200,
        help_text=_("Enter post's text"),
    )
    pub_date = models.DateTimeField(
        _('Created at'),
        auto_now_add=True,
        db_index=True
    )


class Follow(models.Model):
    def __str__(self):
        return f'{self.user.username} follows {self.author.username}' or ''

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name=_('Follower'),
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name=_('Following'),
    )
    pub_date = models.DateTimeField(
        _('Created at'),
        auto_now_add=True,
        db_index=True
    )


class Like(models.Model):
    def __str__(self):
        return f'{self.user}'

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_like',
    )

jessiegram/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post, Comment, Group


class PostForm(forms.ModelForm):
    text = forms.CharField(
        max_length=200,
        widget=forms.Textarea,
        label=_("Enter post's text"),
        required=True,
        help_text=_("Post's text")
    )

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {'group': _('Select group')}


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        max_length=200,
        widget=forms.Textarea,
        label=_("Enter post's text"),
        required=True,
        help_text=_("Post's text")
    )

    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': _('Comment')}


class GroupForm(forms.ModelForm):
    title = forms.CharField(
        max_length=20,
        label=_("Enter text"),
        required=True,
        help_text=_("Name of the group")
    )
    slug = forms.SlugField(
        max_length=15,
        label=_("Enter text with latin symbols"),
        required=True,
        help_text=_("Short link")
    )
    description = forms.CharField(
        max_length=25,
        label=_("Enter text"),
        required=True,
        help_text=_("Description of the group")
    )

    class Meta:
        model = Group
        fields = ['title', 'slug', 'description']

jessiegram/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from .models import Like, Post, Group, User, Follow
from .forms import PostForm, CommentForm, GroupForm
from .paginator import paginator_module


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related(
        'group'
    ).order_by(
        '-pub_date'
    )
    context = {
        'page_obj': paginator_module(request, post_list),
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    post_list = Post.objects.select_related(
        'group'
    ).filter(
        group__title=group
    ).order_by(
        '-pub_date'
    )
    context = {
        'group': group,
        'page_obj': paginator_module(request, post_list),
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    following = False
    yourself = False
    # checking if client is authorized
    if request.user.is_authenticated:
        current_user = request.user
        # checking if client is following this author
        following = Follow.objects.filter(
            user=current_user,
            author=author
        )
        # checking if its clients profile
        if current_user == author:
            yourself = True

    post_list = Post.objects.select_related(
        'group', 'author'
    ).filter(
        author__username=username
    ).order_by(
        '-pub_date'
    )
    context = {
        'username': author,
        'page_obj': paginator_module(request, post_list),
        'post_count': post_list.count(),
        'following': following,
        'yourself': yourself
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    editable = False
    liked = False
    if request.user.is_authenticated:
        current_user = request.user
        liked = Like.objects.filter(user=current_user, post=post_id).exists()
        if current_user == post.author:
            editable = True
    post_count = post.author.posts.count()
    form = CommentForm()
    post_comments = post.comments.all()
    context = {
        'post_id': post_id,
        'post': post,
        'post_count': post_count,
        'form': form,
        'comments': post_comments,
        'editable': editable,
        'liked': liked,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    author = request.user
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        new_post = Post(
            text=form.cleaned_data['text'],
            author=author,
            group=form.cleaned_data['group'],
            image=form.cleaned_data['image']
        )
        new_post.save()
        return redirect(f'/profile/{author}/')
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def group_create(request):
    template = 'posts/create_group.html'
    form = GroupForm(
        request.POST or None,
    )
    if form.is_valid():
        new_group = Group(
            title=form.cleaned_data['title'],
            slug=form.cleaned_data['slug'],
            description=form.cleaned_data['description'],
        )
        new_group.save()
        return redirect('posts:index')
    context = {
        'form': form,
    }

    return render(request, template, context)


def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    author = request.user
    if author == post.author:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            post.save()
            return redirect(f'/posts/{post_id}/')
        context = {
            'form': form,
            'post': post,
            'is_edit': True
        }
        return render(request, template, context)
    return redirect(f'/posts/{post_id}/')


def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    current_user = request.user
    if current_user == post.author:
        print(dir(current_user))
        current_user.posts.filter(id=post_id).delete()
        return redirect('posts:profile', username=current_user.username)
    return redirect(f'/posts/{post_id}/')


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    current_user = request.user
    post_list = Post.objects.select_related(
        'group', 'author'
    ).filter(
        author__following__user=current_user
    ).order_by(
        '-pub_date'
    )
    context = {
        'page_obj': paginator_module(request, post_list),
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    current_user = request.user
    if current_user != author and not (
        current_user.follower.filter(author=author).exists()
    ):
        current_user.follower.create(author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    current_user = request.user
    if current_user != author:
        current_user.follower.filter(author=author).delete()
    return redirect('posts:profile', username=username)


@login_required
def add_or_delete_like(request, post_id):
    current_user = request.user
    post = Post.objects.filter(id=post_id).get()
    liked = Like.objects.filter(user=current_user, post=post_id).exists()
    if not liked:
        Like.objects.create(user=current_user, post=post)
    else:
        Like.objects.filter(user=current_user, post=post).delete()
    return redirect(request.META.get('HTTP_REFERER'))


# @login_required
def set_language(request):
    lang = request.GET.get('l', 'en')
    request.session[settings.LANGUAGE_SESSION_KEY] = lang
    response = HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang)
    return response

jessiegram/templates/posts/create_group.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'New group' %}
{% endblock title %}
{% block content %}
    <div class="row justify-content-center main-bg">
        <div class="col-md-5 p-5">
            <div class="card">
                <div class="card-header">{% trans 'Create group' %}</div>
                <div class="card-body">
                    {% include 'users/includes/form_errors.html' %}
                    <form method="post"
                          {% if action_url %} action="{% url action_url %}" {% endif %}>
                        {% csrf_token %}
                        {% include 'users/includes/form.html' %}
                            <button type="submit" class="btn btn-outline-secondary">{% trans 'Create group' %}</button>
                    </form>
                </div>
                <!-- card body -->
            </div>
            <!-- card -->
        </div>
        <!-- col -->
    </div>
    <!-- row -->
{% endblock content %}

jessiegram/templates/posts/create_post.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'Create new post' %}
{% endblock title %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if not is_edit %}
                            {% trans 'Submit post' %}
                        {% else %}
                            {% trans 'Edit post' %}
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <form method="post" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group row my-3 p-3">
                                {% if is_edit %}
                                    <p>
                                        {% trans 'Text:' %} <b>{{ post.text }}</b>
                                    </p>
                                {% endif %}
                                {% for field in form %}
                                    <div class="form-group row my-3">
                                        <label for="{{ field.id_for_label }}">
                                            {{ field.label }}
                                            {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                                        </label>
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-outline-secondary">
                                        {% if not is_edit %}
                                            {% trans 'Add record' %}
                                        {% else %}
                                            {% trans 'Save' %}
                                        {% endif %}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jessiegram/templates/posts/follow.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {% trans 'Followers' %}
{% endblock title %}
{% block content %}
    <div class="bg-light">
        <div class="container py-5">
            <div class="row">
                {% for post in page_obj %}
                    <div class="col-md-4">{% include "posts/includes/one_post.html" %}</div>
                {% endfor %}
            </div>
            {% include "posts/includes/paginator.html" %}
        </div>
    </div>
{% endblock content %}

jessiegram/templates/posts/group_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {{ group }}
{% endblock title %}
{% block content %}
    {% load thumbnail %}
    {% load i18n %}
    <div class="py-0 custom-background-group">
        <div class="container py-3">
            <div class="bg-white box-shadow custom-container-blob">
                <div class="custom-container-blob80">
                    <h5 class="px-3 custom-text-left">{{ group }}</h5>
                    <div class="px-3 custom-text-left custom-all-grey">
                        <p>
                            {{ group.description }}
                        </p>
                        {% trans 'Posts in the group:' %} {{ page_obj.object_list.count }}
                    </div>
                </div>
            </div>
        </div>
        <div class="container py-3">
            <br />
            <div class="row">
                {% for post in page_obj %}
                    <div class="col-md-4">{% include "posts/includes/one_post.html" %}</div>
                {% endfor %}
            </div>
            {% include "posts/includes/paginator.html" %}
        </div>
    </div>
{% endblock content %}

jessiegram/templates/posts/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    JessieGram
{% endblock title %}
{% block content %}
    <div class="py-0">
        <div class="bg-light">
            <div class="container py-3">
{#                {% load cache %}#}
{#                {% cache 5 index_page page_obj %}#}
                <div class="row">
                    {% for post in page_obj %}
                        <div class="col-md-6 col-lg-4">{% include "posts/includes/one_post.html" %}</div>
                    {% endfor %}
                </div>
{#            {% endcache %}#}
            {% include "posts/includes/paginator.html" %}
        </div>
    </div>
</div>
{% endblock content %}

jessiegram/templates/posts/post_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'Post' %} {{ post|truncatechars:30 }}
{% endblock title %}
{% block content %}
    {% load static %}
    {% load thumbnail %}
    {% load user_filters %}
    <div class="bg-light">
        <div class="row">
            {% if post.image %}
                <div class="col-md-4 py-5">
                    <div class="bg-white box-shadow mx-auto custom-container-detail">
                        {% thumbnail post.image "400x400" crop="center" upscale=False as im %}
                        <a href="{{ post.image.url }}">
                            <img class="col-12 py-3"
                                 alt="some pic uploaded by author"
                                 height=""
                                 width=""
                                 src="{{ im.url }}"/>
                        </a>
                    {% endthumbnail %}
                </div>
            </div>
        {% endif %}
        <div class="col-md-4 py-5">
            <div class="bg-white box-shadow mx-auto position-relative custom-container-detail">
                <div class="px-3">
                    <a href="{% url "posts:profile" post.author %}">@{{ post.author }}</a>
                    {% if post.group %}
                        <p>
                            {% trans 'In the group:' %} <a href="{% url "posts:group_list" post.group.slug %}">{{ post.group }}</a>
                        </p>
                    {% endif %}
                    <p class="custom-wrapper">
                        {{ post.text }}
                    </p>
                    <p>
                        {% if editable %}
                            <a class="btn btn-outline-secondary"
                               href="{% url "posts:post_edit" post_id %}">{% trans 'Edit' %}</a>
                            <a class="btn btn-outline-secondary"
                               href="{% url "posts:post_delete" post_id %}">{% trans 'Delete' %}</a>
                        {% endif %}
                    </p>
                </div>
                <div class="px-3 position-absolute bottom-0 start-0 custom-all-grey">
                    <p>
                        <a href="{% url 'posts:add_or_delete_like' post.id %}">
                            {% if liked %}
                                <img src="{% static 'img/liked.svg' %}" height="20" width="20" alt="like"/>{% else %}
                                <img src="{% static 'img/like.svg' %}" height="20" width="20" alt="like"/>{% endif %}</a>
                            {{ post.likes.count }}
                        <br/>
                        {% trans 'Comments' %} {{ post.comments.count }}
                    </p>
                </div>
                <div class="row px-3 position-absolute bottom-0 end-0 custom-date">
                    <p>
                        {{ post.pub_date|date:"d E Y" }}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% for comment in comments %}
        <br />
        <div class="bg-white box-shadow mx-auto custom-comment">
            <div class="px-3">
                <p>
                    <a href="{% url "posts:profile" comment.author %}">@{{ comment.author }}</a>
                    <br />
                    {{ comment.pub_date|date:"d E Y" }}
                    <br />
                    {{ comment.text }}
                </p>
            </div>
        </div>
        <br />
    {% endfor %}
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 card my-4">
                <h5 class="card-header">{% trans 'Add comment' %}</h5>
                <div class="card-body">
                    <form method="post" action="{% url "posts:add_comment" post.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-2">{{ form.text|addclass:"form-control" }}</div>
                        <button type="submit" class="btn btn-outline-secondary">{% trans 'Send' %}</button>
                    </form>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    {% endif %}
</div>
{% endblock content %}

jessiegram/templates/posts/profile.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'Account' %} {{ username }}
{% endblock title %}
{% block content %}
    {% load thumbnail %}
    <div class="custom-background-profile">
        <div class="container py-3">
            <div class="bg-white box-shadow custom-container-blob">
                <div class="custom-container-blob80">
                    <h5 class="px-3 custom-text-left">@{{ username }}</h5>
                    <div class="px-3 custom-text-left custom-all-grey">
                        <p>
                            {{ username.get_full_name }}
                            <br />
                            {% trans 'Subscribers:' %} {{ username.following.count }}
                            <br />
                            {% trans 'Subscriptions:' %} {{ username.follower.count }}
                            <br />
                            {% trans 'Posts:' %} {{ post_count }}
                        </p>
                    </div>
                    <div class="px-3 px-3">
                        {% if user.is_authenticated %}
                            {% if yourself %}
                            {% else %}
                                {% if following %}
                                    <a class="py-1 btn btn-outline-secondary custom-left-px50"
                                       href="{% url "posts:profile_unfollow" username %}"
                                       role="button">
                                        {% trans 'Unfollow' %}
                                    </a>
                                {% else %}
                                    <a class="py-1 btn btn-outline-secondary custom-left-px50"
                                       href="{% url "posts:profile_follow" username %}"
                                       role="button">
                                        {% trans 'Follow' %}
                                    </a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <br />
        </div>
        <div class="container py-3">
            <div class="row">
                {% for post in page_obj %}
                    <div class="col-md-4">{% include "posts/includes/one_post.html" %}</div>
                {% endfor %}
                {% include "posts/includes/paginator.html" %}
            </div>
        </div>
    </div>
{% endblock content %}