jessiegram/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

jessiegram/jessiegram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('i18n/', include('django.conf.urls.i18n'))
]

handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path(
            '__debug__/',
            include(
                debug_toolbar.urls
            )
        ),
    )

jessiegram/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordResetConfirmView
)

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

jessiegram/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

jessiegram/users/views.py
from django.http import HttpResponseRedirect
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.urls import reverse, reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

    # auto login after register:
    def form_valid(self, form):
        # save the new user first
        form.save()
        # get the username and password
        # username =
        self.request.POST['username']
        # password =
        self.request.POST['password1']
        # authenticate user then login
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
        )
        login(self.request, user)
        return HttpResponseRedirect(reverse('posts:index'))

jessiegram/templates/users/logged_out.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Successfully logout' %}{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% trans 'Logout' %}</div>
            <div class="card-body"> <p>{% trans 'Successfully logout' %}</p>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

jessiegram/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'Login' %}
{% endblock title %}
{% block content %}
    <div class="row justify-content-center main-bg">
        <div class="col-md-3 p-5">
            <div class="card">
                <div class="card-header">{% trans 'Login to the site' %}</div>
                <div class="card-body">
                    {% include 'users/includes/form_errors.html' %}
                    <form method="post"
                          {% if action_url %} action="{% url action_url %}" {% endif %}>
                        {% csrf_token %}
                        {% include 'users/includes/form.html' %}
                            <button type="submit" class="btn btn-outline-secondary">{% trans 'Login' %}</button>
                            <a href="{% url 'users:password_reset' %}"
                               class="btn btn-outline-secondary">{% trans 'Forgot password?' %}</a>
                    </form>
                </div>
                <!-- card body -->
            </div>
            <!-- card -->
        </div>
        <!-- col -->
    </div>
    <!-- row -->
{% endblock content %}

jessiegram/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Password changed successfully' %}{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% trans 'Password changed successfully' %}
        </div>
        <div class="card-body"> 
          <p>{% trans 'Password changed successfully' %}</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock content %}

jessiegram/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Change password' %}{% endblock title %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% trans 'Change password' %}
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'password_change' %}">
            {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                {% trans 'Old password' %}
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                {% trans 'New password' %}
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul>
                    <li>{% trans 'Your password must not be the same as or too similar to your name or other personal information.' %}</li>
                    <li>{% trans 'Your password must be at least 8 characters.' %}</li>
                    <li>{% trans 'Your password cannot be one of the commonly used passwords.' %}</li>
                    <li>{% trans 'Your password cannot be all numbers.' %}</li>
                  </ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                {% trans 'Comfirm new password' %}
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-outline-secondary">
                {% trans 'Change password' %}
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock content %}

jessiegram/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Password was dropped' %}{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% trans 'Password was dropped' %}
              </div>
              <div class="card-body">
                <p>{% trans 'Password was dropped' %}</p>
                <a href="{% url 'login' %}">{% trans 'Login' %}</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock content %}

jessiegram/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'New password' %}{% endblock title %}
{% block content %}
{% load user_filters %}
{% if validlink %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                  {% trans 'Enter the new password' %}
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      {% trans 'New password' %}
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul>
                          <li>{% trans 'Your password must not be the same as or too similar to your name or other personal information.' %}</li>
                          <li>{% trans 'Your password must be at least 8 characters.' %}</li>
                          <li>{% trans 'Your password cannot be one of the commonly used passwords.' %}</li>
                          <li>{% trans 'Your password cannot be all numbers.' %}</li>
                      </ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      {% trans 'Confirm new password' %}
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-outline-secondary">
                      {% trans 'Set new password' %}
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% else %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% trans 'Error' %}
              </div>
              <div class="card-body">
                <p>{% trans 'The password reset link is out of date.' %}</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% endif %}
      </div>
{% endblock content %}

jessiegram/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Password dropped successfully' %}{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                  {% trans 'e-mail sent' %}
              </div>
              <div class="card-body">
                <p>{% trans 'Please check your email with a link to restore' %}</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock content %}

jessiegram/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Сброс пароля{% endblock title %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% trans 'To reset your old password, enter the email address you registered with' %}
              </div>
              <div class="card-body"> 
                <form method="post" action="{% url 'password_reset' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                        {% trans 'email address' %}
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-outline-secondary">
                        {% trans 'Reset password' %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
{% endblock content %}

jessiegram/templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'Signup' %}
{% endblock title %}
{% block content %}
    <div class="row justify-content-center main-bg">
        <div class="col-md-4 p-5">
            <div class="card">
                <div class="card-header">{% trans 'Sign up' %}</div>
                <div class="card-body">
                    {% include 'users/includes/form_errors.html' %}
                    <form method="post" action="{% url 'users:signup' %}">
                        {% csrf_token %}
                        {% include 'users/includes/form.html' %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-outline-secondary">{% trans 'Sign up' %}</button>
                        </div>
                    </form>
                </div>
                <!-- card body -->
            </div>
            <!-- card -->
        </div>
        <!-- col -->
    </div>
    <!-- row -->
{% endblock content %}